// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyoo7oPmOMFr11E4TF4leHWmq_eP1FJ8g',
    appId: '1:642326707737:web:e532e5154d0ee8e7d2b488',
    messagingSenderId: '642326707737',
    projectId: 'insta-clone-59e50',
    authDomain: 'insta-clone-59e50.firebaseapp.com',
    storageBucket: 'insta-clone-59e50.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTHi5n2cZBNBnoBbKlrMixv3J4b8v__T8',
    appId: '1:642326707737:android:b7c4b395d758c38cd2b488',
    messagingSenderId: '642326707737',
    projectId: 'insta-clone-59e50',
    storageBucket: 'insta-clone-59e50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBofGHBbMhAzdzcib8sr2qk6Ch-tc0s3F8',
    appId: '1:642326707737:ios:26c5a205f5f797dcd2b488',
    messagingSenderId: '642326707737',
    projectId: 'insta-clone-59e50',
    storageBucket: 'insta-clone-59e50.appspot.com',
    iosBundleId: 'com.example.actualInstaClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBofGHBbMhAzdzcib8sr2qk6Ch-tc0s3F8',
    appId: '1:642326707737:ios:26c5a205f5f797dcd2b488',
    messagingSenderId: '642326707737',
    projectId: 'insta-clone-59e50',
    storageBucket: 'insta-clone-59e50.appspot.com',
    iosBundleId: 'com.example.actualInstaClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyoo7oPmOMFr11E4TF4leHWmq_eP1FJ8g',
    appId: '1:642326707737:web:d605c615b1606d45d2b488',
    messagingSenderId: '642326707737',
    projectId: 'insta-clone-59e50',
    authDomain: 'insta-clone-59e50.firebaseapp.com',
    storageBucket: 'insta-clone-59e50.appspot.com',
  );
}
